spring:
  application.name: kafka-test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:commerce
    username: root
    password: 1234
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

spring.kafka:
  bootstrap-servers: 10.134.211.25:9092
  consumer:
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
      spring.json.trusted.packages: "*"
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer


spring.output.ansi.enabled: ALWAYS

logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${sys:PID} --- [%15.15t] %-1.100logger{1.} : %m%n%wEx"
spring.jpa.properties.hibernate.globally_quoted_identifiers: true
spring.jpa.properties.hibernate.globally_quoted_identifiers_skip_column_definitions: true


server:
  port: 8090
logging:
  level:
    root: info
